name: Build GUI App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Read version from VERSION file
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymodbus openpyxl pyinstaller

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if [ -f "modbus_exporter_windows.spec" ]; then
            pyinstaller modbus_exporter_windows.spec
          else
            pyinstaller --onefile --windowed --name modbus_exporter main.py
          fi
        shell: bash

      - name: Build with PyInstaller (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          if [ -f "modbus_exporter.spec" ]; then
            pyinstaller modbus_exporter.spec
          else
            pyinstaller --onefile --windowed --name modbus_exporter main.py
          fi
        shell: bash

      - name: Rename executables with version (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd dist
          if [ -f "modbus_exporter.exe" ]; then
            mv "modbus_exporter.exe" "modbus_exporter_v${{ env.VERSION }}_windows.exe"
          fi
          if [ -d "modbus_exporter" ]; then
            mv "modbus_exporter" "modbus_exporter_v${{ env.VERSION }}_windows"
          fi
        shell: bash

      - name: Rename executables with version (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          if [ -f "modbus_exporter" ]; then
            mv "modbus_exporter" "modbus_exporter_v${{ env.VERSION }}_macos"
          fi
          if [ -d "modbus_exporter.app" ]; then
            mv "modbus_exporter.app" "modbus_exporter_v${{ env.VERSION }}_macos.app"
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-modbus-exporter-v${{ env.VERSION }}
          path: dist/*

  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from VERSION file
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: Windows-modbus-exporter-v${{ env.VERSION }}
          path: ./windows-artifacts

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macOS-modbus-exporter-v${{ env.VERSION }}
          path: ./macos-artifacts

      - name: Create ZIP archives
        run: |
          cd windows-artifacts
          zip -r ../modbus_exporter_v${{ env.VERSION }}_windows.zip *
          cd ../macos-artifacts
          zip -r ../modbus_exporter_v${{ env.VERSION }}_macos.zip *
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          name: Modbus Data Exporter v${{ env.VERSION }}
          body: |
            ## Modbus Data Exporter v${{ env.VERSION }}
            
            ### Features:
            - Sensor Pairing Sheet generation
            - Enhanced Diagnostics with signal quality analysis
            - Live Diagnostics View with column visibility controls
            - Version information display with tooltip
            - Excel and CSV export capabilities
            
            ### Bug Fixes:
            - Fixed double .xlsx extension issue
            - Improved GUI stability and resizing
            
            ### Downloads:
            - **Windows**: `modbus_exporter_v${{ env.VERSION }}_windows.zip`
            - **macOS**: `modbus_exporter_v${{ env.VERSION }}_macos.zip`
            
            ### Installation:
            1. Download the appropriate file for your operating system
            2. Extract the ZIP file
            3. Run the executable
            
            **Note**: On macOS, you may need to right-click and select "Open" to bypass security warnings.
          files: |
            modbus_exporter_v${{ env.VERSION }}_windows.zip
            modbus_exporter_v${{ env.VERSION }}_macos.zip
          draft: false
          prerelease: false
